### PR TITLE
fix for issue #31, added options to create a cluster in machines with only private ip address

### PR DESCRIPTION
**Pull request by jainhitesh9998**
added check in connection section to use private ip or public ip based on the configuration

### CODE REVIEW

**Comment by bhavin192** [comment]
@jainhitesh9998 thank you for sending this fix. Can you add details on how you tested this change?

**Comment by jainhitesh9998** [comment]
@bhavin192  I actually created separate yugabyte clusters for both scenarios, with the private ip and public ip and terraform was able to create cluster.

**Comment by iSignal** [comment]
@jainhitesh9998 : thanks for the contribution! 

Can you please add this variable `use_public_ip_for_ssh` to the end of `deploy.tf` file in README.md? That will let others know that this is an option they can use. 

Also, please do add yourself to the https://github.com/yugabyte/yugabyte-db/blob/master/CONTRIBUTORS.md contributors file on the main repo.

**Review by bhavin192 — APPROVED** [review]

**Comment by jainhitesh9998** [comment]
> @jainhitesh9998 : thanks for the contribution!
> 
> Can you please add this variable `use_public_ip_for_ssh` to the end of `deploy.tf` file in README.md? That will let others know that this is an option they can use.
> 
> Also, please do add yourself to the https://github.com/yugabyte/yugabyte-db/blob/master/CONTRIBUTORS.md contributors file on the main repo.

Sure I'll do the same

**Comment by jainhitesh9998** [comment]
I’ve added the config in reader too

**Pull request closed without merging**
